services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-course
    env_file:
      - path: ./.env
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
